### ISSUE TITLE
Can't compile on Mac with OSX15.5 sdk (arm64).

### ISSUE THREAD

**Issue by zacx-z** [pocoproject/poco#5012]
**Describe the bug**
Can't compile on Mac with OSX15.5 sdk (arm64).

**To Reproduce**
> mkdir cmake-build && cd cmake-build
> cmake .. -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release && cmake --build .

**Expected behavior**
Successful compilation

**Logs**

Seems the identifier is conflicted with the macro.

```
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/stdio.h:61:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/_stdio.h:318:7: error: expected identifier or '('
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
/Users/zack/Projects/poco-poco-1.10.1-release/Foundation/src/zutil.h:128:33: note: expanded from macro 'fdopen'
  128 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:16: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
```

**Please add relevant environment information:**
 - Mac Sequoia OSX15.5 arm64
 - POCO 1.10.1 release

**Comment by matejk** [comment]
Version 1.10.1 was released more than 5 years ago. Please use newer release.
