### PR TITLE
2208 merge dnssd

### PR DESCRIPTION
**Pull request by aleks-f**

### CODE REVIEW

**Comment by soroshsabz** [comment]
@aleks-f 

Why close my PR?

What is your problem with my PR?

if you want to new PR, you can tell me to create new one

**Comment by aleks-f** [comment]
Because your pull did not trigger all CI. 

I don't understand why does it matter who creates a pull request. But I do suggest to tread carefully - we expend quite a bit of resources on this project. Contributions are welcome, and we are thankful to anyone who is willing to help. But we have no obligation to accept contributions, and we especially do not have to tolerate being told how to accept them.

**Comment by soroshsabz** [comment]
@aleks-f 

Ok, whatever way you see fit. :)

But if you want to merge my PR, I think, if you reopen #4323 and approve that, maybe PR can run CI.

**Comment by soroshsabz** [comment]
@aleks-f Is there anything I can do to help?

**Comment by soroshsabz** [comment]
you could not find any way to RUN CI on original PR?

**Comment by soroshsabz** [comment]
fixes #2208

File: CMakeLists.txt [hunk 1]
```diff
@@ -180,6 +180,12 @@ option(ENABLE_JSON "Enable JSON" ON)
 option(ENABLE_MONGODB "Enable MongoDB" ON)
 option(ENABLE_DATA_SQLITE "Enable Data SQlite" ON)
 option(ENABLE_REDIS "Enable Redis" ON)
+option(ENABLE_DNSSD "Enable DNSSD" OFF)
+option(ENABLE_DNSSD_DEFAULT "Enable DNSSD Default" OFF)
+
+option(ENABLE_DNSSD_AVAHI "Enable DNSSD Avahi" OFF)
```
Comment (matejk) [inline CMakeLists.txt:186]: Should enabling AVAHI or Bonjour automatically enable DNSSD?

File: DNSSD/Avahi/include/Poco/DNSSD/Avahi/Avahi.h [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+#if defined(_WIN32) && defined(POCO_DLL)
+	#if defined(Avahi_EXPORTS)
+		#define POCO_DNSSD_Avahi_API __declspec(dllexport)
+	#else
+		#define POCO_DNSSD_Avahi_API __declspec(dllimport)
+	#endif
+#endif
+
+
+#if !defined(POCO_DNSSD_Avahi_API)
```
Comment (matejk) [inline DNSSD/Avahi/include/Poco/DNSSD/Avahi/Avahi.h:45]: The `_API` macro shall be defined for non-widows platforms in a way that it is defined in Foundation to be consistent.

File: DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/Bonjour.h [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+#if defined(_WIN32) && defined(POCO_DLL)
+	#if defined(Bonjour_EXPORTS)
+		#define POCO_DNSSD_Bonjour_API __declspec(dllexport)
+	#else
+		#define POCO_DNSSD_Bonjour_API __declspec(dllimport)
+	#endif
+#endif
+
+
+#if !defined(POCO_DNSSD_Bonjour_API)
```
Comment (matejk) [inline DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/Bonjour.h:45]: Same comment as for Avahi.

OTOH shall the API macro be defined for complete DNSSD and not separately for Avahi and Bonjour?

**Review by matejk — CHANGES_REQUESTED** [review]
DNSSD does not compile on macOS with XCode and MacOSX14.4.sdk:

`FindBounjour.cmake` does not set library and include variables on Apple platforms.

After fixing that (DNSSD is a part of CoreServices, no additional include directory required) compile fails because enum value `kDNSServiceFlagsNonBrowsable` is not defined in Apple's dns_sd.h.

```

/Users/matejk/git/github/poco/DNSSD/Bonjour/src/BonjourResponderImpl.cpp:83:60: error: use of undeclared identifier 'kDNSServiceFlagsNonBrowsable'; did you mean 'kDNSServiceFlagsNoAutoRename'?
        if (options & DNSSDResponder::REG_NON_BROWSABLE) flags |= kDNSServiceFlagsNonBrowsable;
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                  kDNSServiceFlagsNoAutoRename
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/dns_sd.h:286:5: note: 'kDNSServiceFlagsNoAutoRename' declared here
    kDNSServiceFlagsNoAutoRename        = 0x8,
    ^

```

It was removed in version [1096.0.2](https://github.com/apple-oss-distributions/mDNSResponder/releases/tag/mDNSResponder-1096.0.2) (January 2020).

Older versions of `dns_sd.h` from (https://github.com/apple-oss-distributions/mDNSResponder) still have this value.

```
    kDNSServiceFlagsNonBrowsable        = 0x2000,
    /* A service registered with the NonBrowsable flag set can be resolved using
     * DNSServiceResolve(), but will not be discoverable using DNSServiceBrowse().
     * This is for cases where the name is actually a GUID; it is found by other means;
     * there is no end-user benefit to browsing to find a long list of opaque GUIDs.
     * Using the NonBrowsable flag creates SRV+TXT without the cost of also advertising
     * an associated PTR record.
     */

```

File: DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/BonjourBrowserImpl.h [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+{
+public:
+	BonjourBrowserImpl(EventLoop& eventLoop);
+		/// Creates the BonjourBrowserImpl.
+
+	~BonjourBrowserImpl();
+		/// Destroys the BonjourBrowserImpl.
+
+	// DNSSDBrowser
+	BrowseHandle browse(const std::string& regType, const std::string& domain, int options, Poco::Int32 networkInterface);
```
Comment (matejk) [inline DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/BonjourBrowserImpl.h:50]: Use override keyword for all overridden virtual functions.

File: DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/BonjourBrowserImpl.h [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+	void onEnumerateBrowseDomainsReply(DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t interfaceIndex, DNSServiceErrorType errorCode, const char* replyDomain);
+	void onEnumerateRegistrationDomainsReply(DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t interfaceIndex, DNSServiceErrorType errorCode, const char* replyDomain);
+    void onQueryRecordReply(DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t interfaceIndex, DNSServiceErrorType errorCode, const char* fullName, uint16_t rrtype, uint16_t rrclass, uint16_t rdlen, const void* rdata, uint32_t ttl);
+	void onResolveHostReply(DNSServiceRef sdRef, DNSServiceFlags flags, uint32_t interfaceIndex, DNSServiceErrorType errorCode, const char* hostname, const struct sockaddr* address, uint32_t ttl);
+
+protected:
+	static void parseTXTRecord(Poco::UInt16 length, const void* data, Service::Properties& properties);
+
+private:
+	typedef std::map<DNSServiceRef, Service> ServiceMap;
```
Comment (matejk) [inline DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/BonjourBrowserImpl.h:70]: Using instead of typedef.

File: DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/BonjourResponderImpl.h [hunk 6]
```diff
@@ -0,0 +1,88 @@
...
+{
+public:
+	BonjourResponderImpl(Poco::DNSSD::DNSSDResponder& owner);
+		/// Creates the BonjourResponder, using the given owner.
+
+	~BonjourResponderImpl();
+		/// Destroys the BonjourResponderImpl.
+
+	// DNSSDResponderImpl
+	DNSSDBrowser& browser();
```
Comment (matejk) [inline DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/BonjourResponderImpl.h:47]: Use override keyword for all overridden virtual functions.

File: DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/EventLoop.h [hunk 7]
```diff
@@ -0,0 +1,120 @@
...
+		/// Must be called after the event loop thread has been stopped.
+
+	void lock();
+		/// Locks the internal mutex.
+
+	void unlock();
+		/// Unlocks the internal mutex.
+
+protected:
+	void run();
```
Comment (matejk) [inline DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/EventLoop.h:78]: Use override keyword for all overridden virtual functions.

File: DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/EventLoop.h [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+	void removeImpl(DNSServiceRef sdRef);
+
+private:
+	typedef std::map<Poco::Net::Socket, DNSServiceRef> SockToRef;
```
Comment (matejk) [inline DNSSD/Bonjour/include/Poco/DNSSD/Bonjour/EventLoop.h:82]: Using instead of typedef.

File: DNSSD/Bonjour/CMakeLists.txt [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
+        $<INSTALL_INTERFACE:include>
+    PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/src
+    )
+target_compile_definitions("${LIBNAME}" PUBLIC ${LIB_MODE_DEFINITIONS})
+
+POCO_INSTALL("${LIBNAME}")
+POCO_GENERATE_PACKAGE("${LIBNAME}")
+
+if (ENABLE_TESTS)
```
Comment (matejk) [inline DNSSD/Bonjour/CMakeLists.txt:35]: Fails if tests are enabled due to non-existing subdirectory.

**Review by matejk — APPROVED** [review]

**Comment by soroshsabz** [comment]
@aleks-f @matejk 

Thanks a lot :)
