### ISSUE TITLE
Android compile with poco-1.7.5  no 'pthread_condattr_setclock' error

### ISSUE THREAD

**Issue by fantwind** [pocoproject/poco#1403]
when compiling poco-1.7.5 with android platform 16 gcc toolchain,I got the following error:
```
src/Event_POSIX.cpp: In constructor 'Poco::EventImpl::EventImpl(bool)':
src/Event_POSIX.cpp:50:54: error: 'pthread_condattr_setclock' was not declared in this scope
  if (pthread_condattr_setclock(&attr, CLOCK_MONOTONIC))
```

And when I google, I got `pthread_condattr_setclock` did not exist in Android version prior 5.0,but `HAVE_PTHREAD_COND_TIMEDWAIT_MONOTONIC` is defined prior to Android 5.0.
Also found this link in github: [Check Android support for pthread_cond_timedwait_monotonic_np](https://github.com/ljbade/libuv-1/commit/a23d5b4f7a0f803e23ff9df6a57ee416d9b31610)

Foundation/src/Semaphore_POSIX.cpp also use the `pthread_condattr_setclock`

**Comment by obiltschnig** [comment]
Oh well, Android...

**Comment by alfeng** [comment]
I'm using Poco v1.7.8.0 and Android NDK vr15c on Windows, and I'm still getting this error.

`Foundation/Event_POSIX.cpp:72:6: error:
      use of undeclared identifier 'pthread_condattr_setclock'; did you mea 'pthread_condattr_setpshared'?
        if (pthread_condattr_setclock(&attr, CLOCK_MONOTONIC))
            ^~~~~~~~~~~~~~~~~~~~~~~~~
            pthread_condattr_setpshared
Android/NDK/build//../sysroot/usr/include\pthread.h:128:5: note: 'pthread_condattr_setpshared' declared here
int pthread_condattr_setpshared(pthread_condattr_t* _Nonnull, int);
    ^
1 error generated.`

I don't get the error if I change my build API level to 21, and I don't get the error if I use NDK v13 -- even though 'pthread_condattr_setclock' doesn't exist in that version of 'pthread' either.  Confusing.
