### ISSUE TITLE
OpenSSL 3.0 support

### ISSUE THREAD

**Issue by swt2c** [pocoproject/poco#3415]
OpenSSL 3.0 was recently released and Fedora is already adopting it for F36.

Poco seems to build okay (with a few warnings), but some tests are failing:

```
The following tests passed:
	Encodings
	XML
	JWT
	JSON
	ActiveRecord
	Zip
	Data
	Util
	DataSQLite
	Net
	Foundation
85% tests passed, 2 tests failed out of 13
Total Test time (real) = 113.11 sec
The following tests FAILED:
	  8 - NetSSL (Failed)
	  9 - Crypto (SEGFAULT)
```

**Comment by stephanger** [comment]
Just an addition: 
If you use Poco build with Open-SSL3.0.1 in Visual Studio 2019 x64, you will get compiler errors in "EVPPKey.h" due to the usage of obsolete/degraded functions.

`1>C:\poco-1.11.1\Crypto\include\Poco\Crypto\EVPPKey.h(300,15): error C4996: 'EVP_PKEY_cmp': Since OpenSSL 3.0
1>C:\poco-1.11.1\Crypto\include\Poco\Crypto\EVPPKey.h(300,15): error C4996: 'EVP_PKEY_cmp': Since OpenSSL 3.0
1>C:\poco-1.11.1\Crypto\include\Poco\Crypto\EVPPKey.h(344,7): error C4996: 'EVP_PKEY_set1_EC_KEY': Since OpenSSL 3.0
1>C:\poco-1.11.1\Crypto\include\Poco\Crypto\EVPPKey.h(344,7): error C4996: 'EVP_PKEY_set1_EC_KEY': Since OpenSSL 3.0
1>C:\poco-1.11.1\Crypto\include\Poco\Crypto\EVPPKey.h(351,7): error C4996: 'EVP_PKEY_set1_RSA': Since OpenSSL 3.0
1>C:\poco-1.11.1\Crypto\include\Poco\Crypto\EVPPKey.h(351,7): error C4996: 'EVP_PKEY_set1_RSA': Since OpenSSL 3.0`

**Comment by aleks-f** [comment]
can't reproduce on windows, will look at fedora issue for 1.12.0

**Comment by aleks-f** [comment]
I checked fedora 36 with openssl 3, and this definitely does not happen in the current 1.12.0 branch, so I'm marking this as fixed and it will be released in 1.1.20
