### ISSUE TITLE
OpenSSL no_deprecated

### ISSUE THREAD

**Issue by GregDomjan** [pocoproject/poco#5415]
**Describe the bug**
Poco fails to build against OpenSSL 3.6.3 that was built with no-deprecated=true

**To Reproduce**
Will investigate small sample project to demonstrate build missing.

openssl/3.6.3
poco/1.15.2

Conan config 

[options]
openssl/*:shared=False
openssl/*:no_deprecated=True
openssl/*:no_legacy=True
poco/*:shared=False

**Expected behavior**
expand current identification in usage of OpenSSL items marked deprecated so that no-deprecated may be used.

**Logs**

/builds/.conan2/p/b/poco6758757fc253f/b/src/NetSSL_OpenSSL/src/SSLManager.cpp: In static member function ‘static int Poco::Net::SSLManager::verifyOCSPResponseCallback(SSL*, void*)’:
/builds/.conan2/p/b/poco6758757fc253f/b/src/NetSSL_OpenSSL/src/SSLManager.cpp:305:20: error: ‘SSL_get_peer_certificate’ was not declared in this scope
  X509* pPeerCert = SSL_get_peer_certificate(pSSL);
                    ^~~~~~~~~~~~~~~~~~~~~~~~
/builds/.conan2/p/b/poco6758757fc253f/b/src/NetSSL_OpenSSL/src/SSLManager.cpp:305:20: note: suggested alternative: ‘SSL_get1_peer_certificate’
  X509* pPeerCert = SSL_get_peer_certificate(pSSL);
                    ^~~~~~~~~~~~~~~~~~~~~~~~
                    SSL_get1_peer_certificate
NetSSL_OpenSSL/CMakeFiles/NetSSL.dir/build.make:327: recipe for target 'NetSSL_OpenSSL/CMakeFiles/NetSSL.dir/src/SSLManager.cpp.o' failed
gmake[2]: *** [NetSSL_OpenSSL/CMakeFiles/NetSSL.dir/src/SSLManager.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/builds/.conan2/p/b/poco6758757fc253f/b/src/NetSSL_OpenSSL/src/SecureSocketImpl.cpp: In member function ‘long int Poco::Net::SecureSocketImpl::verifyPeerCertificateImpl(const string&)’:
/builds/.conan2/p/b/poco6758757fc253f/b/src/NetSSL_OpenSSL/src/SecureSocketImpl.cpp:490:20: error: ‘::SSL_get_peer_certificate’ has not been declared
  ::X509* pCert = ::SSL_get_peer_certificate(_pSSL);
                    ^~~~~~~~~~~~~~~~~~~~~~~~
/builds/.conan2/p/b/poco6758757fc253f/b/src/NetSSL_OpenSSL/src/SecureSocketImpl.cpp:490:20: note: suggested alternative: ‘SSL_get1_peer_certificate’
  ::X509* pCert = ::SSL_get_peer_certificate(_pSSL);
                    ^~~~~~~~~~~~~~~~~~~~~~~~
                    SSL_get1_peer_certificate
/builds/.conan2/p/b/poco6758757fc253f/b/src/NetSSL_OpenSSL/src/SecureSocketImpl.cpp: In member function ‘X509* Poco::Net::SecureSocketImpl::peerCertificate() const’:
/builds/.conan2/p/b/poco6758757fc253f/b/src/NetSSL_OpenSSL/src/SecureSocketImpl.cpp:519:12: error: ‘::SSL_get_peer_certificate’ has not been declared
   return ::SSL_get_peer_certificate(_pSSL);
            ^~~~~~~~~~~~~~~~~~~~~~~~
/builds/.conan2/p/b/poco6758757fc253f/b/src/NetSSL_OpenSSL/src/SecureSocketImpl.cpp:519:12: note: suggested alternative: ‘SSL_get1_peer_certificate’
   return ::SSL_get_peer_certificate(_pSSL);
            ^~~~~~~~~~~~~~~~~~~~~~~~
            SSL_get1_peer_certificate

**Please add relevant environment information:**
 - OS Type and Version: Linux, SUSE 12 SP5
 - POCO Version: 1.15.2
 - Built from conan2 recipe,  gcc8

https://github.com/pocoproject/poco/blob/1dd27806a26477c0771a4f863039af4c18696afe/NetSSL_OpenSSL/src/SSLManager.cpp#L304
https://github.com/pocoproject/poco/blob/1dd27806a26477c0771a4f863039af4c18696afe/NetSSL_OpenSSL/src/SSLManager.cpp#L15-L17
https://github.com/pocoproject/poco/blob/1dd27806a26477c0771a4f863039af4c18696afe/NetSSL_OpenSSL/src/SecureSocketImpl.cpp#L489
https://github.com/pocoproject/poco/blob/1dd27806a26477c0771a4f863039af4c18696afe/NetSSL_OpenSSL/src/SecureSocketImpl.cpp#L518

**Additional context**
AI Overview                 
In OpenSSL 3.0, SSL_get_peer_certificate has been deprecated. It is replaced by SSL_get1_peer_certificate or SSL_get0_peer_certificate, which handle certificate reference counting explicitly.If you are upgrading an older codebase to OpenSSL 3, you will likely see compilation warnings or linker errors like undefined reference to SSL_get_peer_certificate if your environment compiles with OPENSSL_NO_DEPRECATED enabled.

Recommended Replacements
You should modify your code to use one of the two new functions depending on how you manage memory:
SSL_get1_peer_certificate() [1](https://manpages.debian.org/experimental/libssl-doc/SSL_get_peer_certificate.3ssl.en.html)

Behavior: Identical to the deprecated function.
Memory Management: It increments the reference count of the X509 object.
Action Required: You must explicitly free the pointer using X509_free() when you are done with it to avoid memory leaks.

SSL_get0_peer_certificate()
Behavior: Returns a pointer to the internal certificate object.
Memory Management: It does not increment the reference count.
Action Required: Do not free this pointer. The memory is tied to the lifecycle of the SSL connection object.

**Comment by GregDomjan** [comment]
Working on updated Conan recipe for 1.15.3, compile on Windows vc142/VS2019  - issue is not platform specific.

>  VerificationErrorArgs.cpp
C:\build\.conan2\p\b\pococ3274fbf8ed9e\b\src\NetSSL_OpenSSL\src\SSLManager.cpp(305,20): error C3861: 'SSL_get_peer_certificate': identifier not found [C:\U
sers\gdomjan\.conan2\p\b\pococ3274fbf8ed9e\b\build\NetSSL_OpenSSL\NetSSL.vcxproj]
  X509Certificate.cpp
C:\build\.conan2\p\b\pococ3274fbf8ed9e\b\src\NetSSL_OpenSSL\src\SecureSocketImpl.cpp(490,20): error C2039: 'SSL_get_peer_certificate': is not a member of '
`global namespace'' [C:\build\.conan2\p\b\pococ3274fbf8ed9e\b\build\NetSSL_OpenSSL\NetSSL.vcxproj]
C:\build\.conan2\p\b\pococ3274fbf8ed9e\b\src\NetSSL_OpenSSL\src\SecureSocketImpl.cpp(490,44): error C3861: 'SSL_get_peer_certificate': identifier not found
 [C:\build\.conan2\p\b\pococ3274fbf8ed9e\b\build\NetSSL_OpenSSL\NetSSL.vcxproj]
C:\build\.conan2\p\b\pococ3274fbf8ed9e\b\src\NetSSL_OpenSSL\src\SecureSocketImpl.cpp(519,12): error C2039: 'SSL_get_peer_certificate': is not a member of '
`global namespace'' [C:\build\.conan2\p\b\pococ3274fbf8ed9e\b\build\NetSSL_OpenSSL\NetSSL.vcxproj]
C:\build\.conan2\p\b\pococ3274fbf8ed9e\b\src\NetSSL_OpenSSL\src\SecureSocketImpl.cpp(519,36): error C3861: 'SSL_get_peer_certificate': identifier not found
 [C:\build\.conan2\p\b\pococ3274fbf8ed9e\b\build\NetSSL_OpenSSL\NetSSL.vcxproj]

Patching via preprocessor allows workaround

``` python
        if "openssl" in self.dependencies and Version(self.dependencies["openssl"].ref.version) >= "3":
            tc.preprocessor_definitions["SSL_get_peer_certificate"] = "SSL_get1_peer_certificate"
```

**Comment by GregDomjan** [comment]
Follow up issue in Debug builds only with RSA and EC_KEY

[0008-fix-openssl-nodeprecated-debug-assert.patch](https://github.com/user-attachments/files/30370045/0008-fix-openssl-nodeprecated-debug-assert.patch)

**Comment by matejk** [comment]
Should be fixed in #5313 already.

**Comment by matejk** [comment]
Correction to my earlier comment: the Debug-only assert failure was not covered by #5313 -- the `typeid(RSA*)`/`typeid(EC_KEY*)` asserts in `EVPPKey.h` were untouched. #5416 fixes both that (based on your patch, thanks @GregDomjan) and the three remaining `SSL_get_peer_certificate` calls in NetSSL, and adds a CI job so no-deprecated builds stay covered.
