### ISSUE TITLE
Cannot build in OSX Big Sur 11.2

### ISSUE THREAD

**Issue by stephb9959** [pocoproject/poco#3214]
Hi,

I am using Poco already (installed from brew) but needed to add the PostgreSQL connector. So I decided to build from source. Got the 1.10.1 full tar file provided. 

With or without the PostgreSQL client installed, I get the following error when building using cmake (74% through the full compile)

`In file included from /Users/stephb/Desktop/poco-build/poco-1.10.1-all/Crypto/src/CipherFactory.cpp:18:
In file included from /Users/stephb/Desktop/poco-build/poco-1.10.1-all/Crypto/include/Poco/Crypto/RSAKey.h:23:
In file included from /Users/stephb/Desktop/poco-build/poco-1.10.1-all/Crypto/include/Poco/Crypto/RSAKeyImpl.h:22:
/Users/stephb/Desktop/poco-build/poco-1.10.1-all/Crypto/include/Poco/Crypto/EVPPKey.h:305:23: error: use of undeclared identifier
      'EVP_PKEY_id'
        return EVP_PKEY_type(EVP_PKEY_id(pEVPPKey));
                             ^
1 error generated.
gmake[2]: *** [Crypto/CMakeFiles/Crypto.dir/build.make:95: Crypto/CMakeFiles/Crypto.dir/src/CipherFactory.cpp.o] Error 1
`

Just wondering if anyone has found the same problem.

I also tried master from git and the 1.10.2 branches. Same problem.

Thanks

**Comment by keefo** [comment]
I am able to build poco on Big Sur 11.2.1 (20D74).
You'd better review your openssl version. and Mine is
[/usr/local/opt/openssl/bin]$ ./openssl version
OpenSSL 1.1.1j  16 Feb 2021

**Comment by stephb9959** [comment]
@keefo , I just checked and I have the exact same version of openssl you have. Installed from brew. 

But you gave me an idea. I was able to force cmake to use the proper OpenSSL directory:

`cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..`

That allowed me to build. Now I just have to figure out how to get PostgreSQL::client to link...

Thanks
