### ISSUE TITLE
Cannot compile on gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3 using compiler flag pedantic

### ISSUE THREAD

**Issue by tinobog** [pocoproject/poco#26]
We started using POCO -1.4.5 in our project (was 1.3.6). When we compile heaps of warnings/errors in that fashion pop up:
poco-1.4.5/include/Poco/Exception.h:274:74: error: invoking macro POCO_DECLARE_EXCEPTION_CODE argument 1: empty macro arguments are undefined in ISO C90 and ISO C++98 

In this version of POCO calls to a macro called POCO_DECLARE_EXCEPTION are forwarded to POCO_DECLARE_EXCEPTION_CODE. Since we are working on linux the macro FOUNDATION_API is empty and nothing reaches POCO_DECLARE_EXCEPTION_CODE as first argument.

Is the forwarding necessary? Could FOUNDATION_API be set to some dummy statement?

We do want compile using pedantic, to keep our code base as clean and stable as possible.
