### ISSUE TITLE
Net fails to build with MinGW 9.20

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#2965]
```
gcc (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[ 49%] Built target JSON
[ 54%] Built target Util
[ 54%] Building CXX object Net/CMakeFiles/Net.dir/src/ICMPPacket.cpp.obj
In file included from e:\apps\mingw171\x86_64-w64-mingw32\include\mprapi.h:16,
                from e:\apps\mingw171\x86_64-w64-mingw32\include\iprtrmib.h:12,
                from e:\apps\mingw171\x86_64-w64-mingw32\include\iphlpapi.h:15,
                from E:/POCO/1.10.1/Foundation/include/Poco/UnWindows.h:33,
                from E:/POCO/1.10.1/Foundation/include/Poco/Platform_WIN32.h:22,
                from E:/POCO/1.10.1/Foundation/include/Poco/Foundation.h:100,
                from E:/POCO/1.10.1/Net/include/Poco/Net/ICMPPacket.h:21,
                from E:\POCO\1.10.1\Net\src\ICMPPacket.cpp:15:
E:/POCO/1.10.1/Net/include/Poco/Net/ICMPv4PacketImpl.h:72:3: error: expected identifier before '(' token
  72 |   TIMESTAMP_REQUEST,
     |   ^~~~~~~~~~~~~~~~~
E:/POCO/1.10.1/Net/include/Poco/Net/ICMPv4PacketImpl.h:72:3: error: expected '}' before '(' token
In file included from E:\POCO\1.10.1\Net\src\ICMPPacket.cpp:16:
E:/POCO/1.10.1/Net/include/Poco/Net/ICMPv4PacketImpl.h:58:2: note: to match this '{'
  58 |  {
     |  ^
In file included from e:\apps\mingw171\x86_64-w64-mingw32\include\mprapi.h:16,
                from e:\apps\mingw171\x86_64-w64-mingw32\include\iprtrmib.h:12,
                from e:\apps\mingw171\x86_64-w64-mingw32\include\iphlpapi.h:15,
                from E:/POCO/1.10.1/Foundation/include/Poco/UnWindows.h:33,
                from E:/POCO/1.10.1/Foundation/include/Poco/Platform_WIN32.h:22,
                from E:/POCO/1.10.1/Foundation/include/Poco/Foundation.h:100,
                from E:/POCO/1.10.1/Net/include/Poco/Net/ICMPPacket.h:21,
                from E:\POCO\1.10.1\Net\src\ICMPPacket.cpp:15:
```

**Comment by sk-landry** [comment]
Hi there, I just created an issue for that here
https://github.com/pocoproject/poco/issues/2967

**Comment by matejk** [comment]
Resolved in #4343 .
