### ISSUE TITLE
Crypto library does not build with OpenSSL 0.9.8b

### ISSUE THREAD

**Issue by agalanin** [pocoproject/poco#2627]
#### Expected behavior
Successful compilation with OpenSSL 0.9.8.
#### Actual behavior
```
[ 86%] Building CXX object Crypto/CMakeFiles/Crypto.dir/src/CipherFactory.cpp.o
In file included from /BUILD/poco/Crypto/include/Poco/Crypto/RSAKeyImpl.h:22:0,
                 from /BUILD/poco/Crypto/include/Poco/Crypto/RSAKey.h:23,
                 from /BUILD/poco/Crypto/src/CipherFactory.cpp:18:
/BUILD/poco/Crypto/include/Poco/Crypto/EVPPKey.h:25:24: fatal error: openssl/ec.h: No such file or directory
 #include <openssl/ec.h>
```
#### Steps to reproduce the problem
Build on CentOS 5.0. Unfortunately RHEL 5.x/CentOS 5.x is not dead yet (extended support is continued until 11/2020) :(

#### POCO version
1.9.0
#### Compiler and version
g++ (GCC) 6.3.0
#### Operating system and version
CentOS 5.0
