### ISSUE TITLE
Net: pocoNetworkInitializer not exported when PocoNet.dll is built with clang-cl

### ISSUE THREAD

**Issue by pavledragisic** [pocoproject/poco#5368]
**Describe the bug**

PR #5205 widened the `POCO_NET_FORCE_SYMBOL` guard in
`Net/include/Poco/Net/Net.h` to `#if defined(POCO_COMPILER_MINGW) || defined(__clang__)`.
`__clang__` is also defined for clang-cl, which uses the MSVC ABI. This
routes clang-cl into the MinGW branch, so a clang-cl-built `PocoNet.dll`
never emits `/export:pocoNetworkInitializer`. DLL consumers (MSVC or
clang-cl) then fail to link with `LNK2001: unresolved external symbol
pocoNetworkInitializer`.

**To Reproduce**

1. Build PocoNet shared with clang-cl.
2. `dumpbin /exports PocoNet.dll | findstr /i pocoNetwork` → no output.
3. Link any DLL that includes `Poco/Net/Net.h` → `LNK2001`.

**Expected behavior**

clang-cl should follow the MSVC `/export:` / `/include:` path; the
symbol should appear in `dumpbin /exports`.

**Environment**

- Windows 10/11 x64
- POCO `main` (regression from #5205, 21c95af)
- clang-cl (LLVM), consumer built with MSVC `cl.exe`
- Shared build (`POCO_DLL`, `Net_EXPORTS`)
