### ISSUE TITLE
Unable to compile Poco::Data for Windows Compact Embedded 2013

### ISSUE THREAD

**Issue by bachp** [pocoproject/poco#1252]
When compiling Poco for Windows CE 2013 the compilation terminates with the following error:

```
00:54:50.623 c:\program files (x86)\windows ce tools\sdks\sdk_am335x_sk_wec2013_v310\sdk\crt\include\stl\xutility(635): fatal error C1128: number of sections exceeded object file format limit : compile with /bigobj [poco_WinCE_LATEST\Data\Data_WEC2013_vs120.vcxproj]
```

Bisecting shows that the problem was introduced with commit 32f3f4a1466774b88a547dc0adbf982dad07cb15

The build is started using the following command:

```
call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\vsvars32.bat"
SET WEC2013_PLATFORM=SDK_AM335X_SK_WEC2013_V310
buildwin 120 rebuild all both WEC2013 nosamples
```

**Comment by bachp** [comment]
@obiltschnig Any idea how this could be fixed?

**Comment by zosrothko** [comment]
@bachp  May be as stated in the error message: `compile with /bigobj`

**Comment by bachp** [comment]
@zosrothko Looks like the `/bigobj` is missing in `Data_WEC2013_vs110.sln` and `Data_WEC2013_vs120.sln`.

I'm not to familiar with ProGen maybe you can help me out how to add this?

**Comment by zosrothko** [comment]
Data.progen contains the following line
vc.project.compiler.additionalOptions.x64 = /bigobj

I presume that adding
vc.project.compiler.additionalOptions.Win32 = /bigobj

will do the trick

**Comment by bachp** [comment]
Maybe this is a stupid question but how do I tell progen to recreate the project files?

**Comment by aleks-f** [comment]
In this case, it would be `progen Data.progen`

**Comment by bachp** [comment]
I can't get it working.

```
..\bin\progen.exe Data.progen
Not found: progen.project.guidFromName.namespaceUUID
```

Any idea what I'm doing wrong?

**Comment by bachp** [comment]
The issue seems to be gone on the develop branch. It's compiling again since last week.

**Comment by bachp** [comment]
The issue popped up again.

@obiltschnig Is it possible to add `/bigobj` to the Data.progen for Windows CE?

**Comment by obiltschnig** [comment]
Yes, add:
    vc.project.compiler.additionalOptions.WinCE = /bigobj

**Comment by bachp** [comment]
The problem is that I can't get progen running to regenerate the projects :(

**Comment by obiltschnig** [comment]
I have re-generated the Data project files in the develop branch.

**Comment by obiltschnig** [comment]
Note to @obiltschnig: Must also re-generate in the poco-1.7.5 and poco-1.8.0 branches.

**Comment by bachp** [comment]
@obiltschnig thanks for the fix. The issue is resolved.
