### ISSUE TITLE
poco 1.6.1 does not compile with clang 3.8 on ubuntu 14.04

### ISSUE THREAD

**Issue by jbulow** [pocoproject/poco#928]
Poco/MemoryStream.h:87:12: error: enumeration
      value '_S_ios_seekdir_end' not handled in switch [-Werror,-Wswitch]
                        switch (way)
                                ^
/media/ssd/jonasbu/develop-clang/artifacts/external/poco/deliverables/interface/Poco/MemoryStream.h:113:12: error: enumeration
      value '_S_ios_seekdir_end' not handled in switch [-Werror,-Wswitch]
                        switch (way)

**Comment by obiltschnig** [comment]
This must be some stupid compiler or stdlib error. The switch handles std::ios_base::beg, std::ios_base::cur and std::ios_base::end, and there aren't any other cases to handle.

**Comment by kimgr** [comment]
Yes, `_S_ios_seekdir_end` is defined as an end-marker in `std::ios_base` in GNU's libstdc++, see https://github.com/gcc-mirror/gcc/blob/7c62dfbbcd3699efcbbadc9fb3aa14f23a123add/libstdc%2B%2B-v3/include/bits/ios_base.h#L187. This doesn't seem very useful.

I'm working on setting up a Clang/libstdc++ environment so I can test a patch disabling the warning for this function, hoping that would be acceptable.

**Comment by obiltschnig** [comment]
Thought about it, but not sure there's a good solution.
One possible solution is to add a default case (with a comment describing the situation), but this could result in a warning with other toolchains due to potential unreachable code or so. Will have to test. Or replace the switch with an if else chain.

**Comment by kimgr** [comment]
This patch appears to work for me:

    diff --git a/Foundation/include/Poco/MemoryStream.h b/Foundation/include/Poco/MemoryStream.h
    index 7fc6121..2fdca81 100644
    --- a/Foundation/include/Poco/MemoryStream.h
    +++ b/Foundation/include/Poco/MemoryStream.h
    @@ -74,6 +74,10 @@ public:
     		return char_traits::eof();
     	}
 
    +#if defined(__clang__)
    +#pragma clang diagnostic push // Don't warn about unhandled enumeration value in seekdir.
    +#pragma clang diagnostic ignored "-Wswitch"
    +#endif
     	virtual pos_type seekoff(off_type off, std::ios_base::seekdir way, std::ios_base::openmode     which = std::ios_base::in | std::ios_base::out)
     	{
     		const pos_type fail = off_type(-1);
    @@ -133,6 +137,9 @@ public:
     
     		return newoff;
     	}
    +#if defined(__clang__)
    +#pragma clang diagnostic pop
    +#endif
 
     	virtual int sync()
     	{

I think this is the most local change you can make. Switching to an if/else chain would probably work too, but a `default` label might get in trouble with other switch-warnings (some conventions prohibit `default` and require fully covered switches, which is sort of what we're seeing here already.)

**Comment by kimgr** [comment]
Clang has a (somewhat magical) `-Weverything` flag that overrides all other disablements and appears to be extra strict. Neither `default` nor my suggested in-code disabling survive `-Weverything`, but the if/else chain does, so maybe that's the best way forward.

**Comment by obiltschnig** [comment]
I agree. if/else chain may be best solution for now.

**Comment by zosrothko** [comment]
You should use POCO_COMPILER_CLANG instead of __clang__. That's cut the dependencies between the Poco code and specific compiler/OS flags.
