### ISSUE TITLE
c++11 branch & gcc 4.6:compilation failed

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#1102]
Hi
The c++ branch at pocoproject/poco does not compile with gcc 4.6 while it should
** Creating dependency info for src/Format.cpp

/usr/include/c++/4.6/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.

**Comment by zosrothko** [comment]
Fixed by https://github.com/RangelReale/poco/commit/0d03ab22bd00041dc7c0f6e025eaef6f8a4d4050

**Comment by ARAVINDAARONE** [comment]
error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
Thread_simple1.cpp: In function 'int main()':
Thread_simple1.cpp:32:5: error: 'thread' was not declared in this scope
     thread t1(func);
     ^
Thread_simple1.cpp:32:12: error: expected ';' before 't1'
     thread t1(func);
            ^
Thread_simple1.cpp:33:5: error: 't1' was not declared in this scope
     t1.join();


Hello i facing issue while running my thread program in VS Code
can you support me in resolving this issue

**Comment by matejk** [comment]
@ARAVINDAARONE , which version of Poco did you try to compile and which compiler did you use?

Poco 1.13 and newer requires compiler that supports standard C++17.

**Comment by ARAVINDAARONE** [comment]
i use C++ 14 which is mingw compiler

**Comment by matejk** [comment]
How do you build Poco? With CMake?

**Comment by ARAVINDAARONE** [comment]
not with CMake, but with the terminal ctr run

**Comment by matejk** [comment]
Then I assume that you did not specify the c++ standard option. It must be set to `std=c++17`.

**Comment by ARAVINDAARONE** [comment]
These are the cpp_properties.json file looks like,

{
    "configurations": [
        {
            "name": "windows-gcc-x86",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "compilerPath": "C:/Softwares/Mingw_posix_Thread_C++/x64-4.8.1-release-posix-sjlj-rev5/mingw64/bin/gcc.exe",
            "cStandard": "c23",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-gcc-x86",
            "compilerArgs": [
                ""
            ]
        }
    ],
    "version": 4
}

**Comment by matejk** [comment]
If `x64-4.8.1-release-posix-sjlj-rev5` indicated version of the GCC compiler then it waaay too old.

You need version 8 or newer.

**Comment by ARAVINDAARONE** [comment]
@matejk after installing Mingw version 8, it works fine,
Thanks for your support
