### ISSUE TITLE
Poco 1.9.1 branch cmake build on FreeBSD 11.1 failed

### ISSUE THREAD

**Issue by astlin** [pocoproject/poco#2398]
#### Expected behavior

Build poco libs

#### Actual behavior

Build poco libs failed

#### Steps to reproduce the problem

```
./configure --no-samples --no-tests --omit=Data/MySQL,Data/SQLite,Data/ODBC
Configured for FreeBSD

make
[  0%] Building CXX object Foundation/CMakeFiles/Foundation.dir/src/ASCIIEncoding.cpp.o
In file included from /home/uzurik/libs/poco/Foundation/src/ASCIIEncoding.cpp:15:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/ASCIIEncoding.h:21:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Foundation.h:163:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Bugcheck.h:22:
In file included from /usr/include/c++/v1/string:470:
In file included from /usr/include/c++/v1/string_view:171:
In file included from /usr/include/c++/v1/__string:57:
/usr/include/c++/v1/cstdio:121:9: error: no member named 'snprintf' in the global namespace
using ::snprintf;
      ~~^
/usr/include/c++/v1/cstdio:125:9: error: no member named 'vfscanf' in the global namespace; did you mean 'fscanf'?
using ::vfscanf;
      ~~^
/usr/include/stdio.h:258:6: note: 'fscanf' declared here
int      fscanf(FILE * __restrict, const char * __restrict, ...);
         ^
In file included from /home/uzurik/libs/poco/Foundation/src/ASCIIEncoding.cpp:15:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/ASCIIEncoding.h:21:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Foundation.h:163:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Bugcheck.h:22:
In file included from /usr/include/c++/v1/string:470:
In file included from /usr/include/c++/v1/string_view:171:
In file included from /usr/include/c++/v1/__string:57:
/usr/include/c++/v1/cstdio:126:9: error: no member named 'vsscanf' in the global namespace; did you mean 'sscanf'?
using ::vsscanf;
      ~~^
/usr/include/stdio.h:278:6: note: 'sscanf' declared here
int      sscanf(const char * __restrict, const char * __restrict, ...);
         ^
In file included from /home/uzurik/libs/poco/Foundation/src/ASCIIEncoding.cpp:15:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/ASCIIEncoding.h:21:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Foundation.h:163:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Bugcheck.h:22:
In file included from /usr/include/c++/v1/string:470:
In file included from /usr/include/c++/v1/string_view:171:
In file included from /usr/include/c++/v1/__string:57:
/usr/include/c++/v1/cstdio:127:9: error: no member named 'vsnprintf' in the global namespace
using ::vsnprintf;
      ~~^
/usr/include/c++/v1/cstdio:164:9: error: no member named 'vscanf' in the global namespace
using ::vscanf;
      ~~^
In file included from /home/uzurik/libs/poco/Foundation/src/ASCIIEncoding.cpp:15:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/ASCIIEncoding.h:21:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Foundation.h:163:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Bugcheck.h:22:
In file included from /usr/include/c++/v1/string:474:
In file included from /usr/include/c++/v1/cwchar:107:
In file included from /usr/include/c++/v1/cwctype:54:
/usr/include/c++/v1/cctype:106:9: error: no member named 'isblank' in the global namespace
using ::isblank;
      ~~^
In file included from /home/uzurik/libs/poco/Foundation/src/ASCIIEncoding.cpp:15:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/ASCIIEncoding.h:21:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Foundation.h:163:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Bugcheck.h:22:
In file included from /usr/include/c++/v1/string:474:
/usr/include/c++/v1/cwchar:127:9: error: no member named 'vfwscanf' in the global namespace; did you mean 'fwscanf'?
using ::vfwscanf;
      ~~^
/usr/include/wchar.h:120:5: note: 'fwscanf' declared here
int     fwscanf(FILE * __restrict, const wchar_t * __restrict, ...);
        ^
In file included from /home/uzurik/libs/poco/Foundation/src/ASCIIEncoding.cpp:15:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/ASCIIEncoding.h:21:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Foundation.h:163:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Bugcheck.h:22:
In file included from /usr/include/c++/v1/string:474:
/usr/include/c++/v1/cwchar:128:9: error: no member named 'vswscanf' in the global namespace; did you mean 'swscanf'?
using ::vswscanf;
      ~~^
/usr/include/wchar.h:133:5: note: 'swscanf' declared here
int     swscanf(const wchar_t * __restrict, const wchar_t * __restrict, ...);
        ^
In file included from /home/uzurik/libs/poco/Foundation/src/ASCIIEncoding.cpp:15:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/ASCIIEncoding.h:21:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Foundation.h:163:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Bugcheck.h:22:
In file included from /usr/include/c++/v1/string:474:
/usr/include/c++/v1/cwchar:138:9: error: no member named 'wcstof' in the global namespace
using ::wcstof;
      ~~^
/usr/include/c++/v1/cwchar:139:9: error: no member named 'wcstold' in the global namespace
using ::wcstold;
      ~~^
/usr/include/c++/v1/cwchar:142:9: error: no member named 'wcstoll' in the global namespace
using ::wcstoll;
      ~~^
/usr/include/c++/v1/cwchar:146:9: error: no member named 'wcstoull' in the global namespace; did you mean 'wcstoul'?
using ::wcstoull;
      ~~^
/usr/include/wchar.h:168:3: note: 'wcstoul' declared here
         wcstoul(const wchar_t * __restrict, wchar_t ** __restrict, int);
         ^
In file included from /home/uzurik/libs/poco/Foundation/src/ASCIIEncoding.cpp:15:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/ASCIIEncoding.h:21:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Foundation.h:163:
In file included from /home/uzurik/libs/poco/Foundation/include/Poco/Bugcheck.h:22:
In file included from /usr/include/c++/v1/string:474:
/usr/include/c++/v1/cwchar:181:9: error: no member named 'vwscanf' in the global namespace
using ::vwscanf;
      ~~^
13 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/uzurik/libs/poco
*** Error code 1

Stop.
make[1]: stopped in /usr/home/uzurik/libs/poco
*** Error code 1

Stop.
make: stopped in /usr/home/uzurik/libs/poco
```

#### POCO version

Poco 1.9.1

#### Compiler and version
```
gcc7 -v
Using built-in specs.
COLLECT_GCC=gcc7
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc7/gcc/x86_64-portbld-freebsd11.1/7.3.0/lto-wrapper
Target: x86_64-portbld-freebsd11.1
Configured with: /wrkdirs/usr/ports/lang/gcc7/work/gcc-7.3.0/configure --with-build-config=bootstrap-debug --disable-nls --enable-gnu-indirect-function --libdir=/usr/local/lib/gcc7 --libexecdir=/usr/local/libexec/gcc7 --program-suffix=7 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc7/include/c++/ --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --enable-languages=c,c++,objc,fortran --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/info/gcc7 --build=x86_64-portbld-freebsd11.1
Thread model: posix
gcc version 7.3.0 (FreeBSD Ports Collection)

```

#### Operating system and version

```
uname -a
FreeBSD newkor 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by aleks-f** [comment]
I don't have a FreeBSD handy to reproduce right now, but from looking at the output, a couple of observations:

- it appears you are configuring make, but using CMake build
- these errors do not look like poco, but rather build environment, issues (eg. `Bugcheck.h` simply includes `<string>` and things go bad up the include chain for some reason)

**Comment by Bjoe** [comment]
Hi. I fixed the the cmake build on FreeBSD. Please test my branch. See pull request #2476
