### ISSUE TITLE
build on  Ubuntu 16.04.7 LTS : fails 

### ISSUE THREAD

**Issue by tecbea** [pocoproject/poco#3879]
Hi
on a Ubuntu 16.04.7 LTS the last build fails on thread_posix:

`
		truncName.append(threadName, threadName.size() - half);

/home/filipec/workspace/poco/poco/Foundation/src/Thread_POSIX.cpp:125:56: note:   deduced conflicting types for parameter ‘_InputIterator’ (‘std::__cxx11::basic_string<char>’ and ‘long unsigned int’)

`

also fails on:

`
[ 74%] Building CXX object Crypto/CMakeFiles/Crypto.dir/src/Envelope.cpp.o
/home/filipec/workspace/poco/poco/Crypto/src/Envelope.cpp: In constructor ‘Poco::Crypto::Envelope::Envelope(int)’:
/home/filipec/workspace/poco/poco/Crypto/src/Envelope.cpp:32:36: error: invalid operands of types ‘int’ and ‘void’ to binary ‘operator!=’
  if (1 != EVP_CIPHER_CTX_init(_pCtx))

`
