### ISSUE TITLE
Compiler error when passing const variable to Poco::Data::Keywords::use() in Poco 1.6

### ISSUE THREAD

**Issue by danatata** [pocoproject/poco#914]
When I passed a const variable to Poco::Data::Keywords::use() as follows in Poco 1.6, 
/////////////
void MyClass::foo(const uint32_t& id) {
	...
	session << "DELETE FROM templates WHERE id = :id",  Poco::Data::Keywords::use(id), PocoNow;
	...
/////////////
I got a compiler error:

...include/Poco/Foundation.h:148:0, from C:/git/remote_targets/remote_headers/linux_x86_64_gcc491_cam_valloy6/usr/include/Poco/Mutex.h:23, from C:/my_project/src/myclass.cc:9: 
/usr/include/Poco/Data/Binding.h: In instantiation of 'Poco::Data::AbstractBinding::Ptr Poco::Data::Keywords::use(T&, const string&) [with T = const unsigned int; Poco::Data::AbstractBinding::Ptr = Poco::SharedPtr<Poco::Data::AbstractBinding>; std::string = std::basic_string<char>]':
C:/my_project/src/myclass.cc:xx:yy:   required from here
/usr/include/Poco/Data/Binding.h:1393:2: error: invalid application of 'sizeof' to incomplete type 'POCO_STATIC_ASSERTION_FAILURE<false>'
  poco_static_assert (!IsConst<T>::VALUE);
  ^

The same code works in Poco 1.4.6 but not compilable in Poco 1.6
Is this an known bug?

**Comment by aleks-f** [comment]
For references, use ```bind()``` or ```useRef()```, not ```use()```. See [here](https://github.com/pocoproject/poco/blob/375eca2ec4df30f0d86b8bca447f30ce9c96a000/Data/include/Poco/Data/Binding.h#L1389) why.
