### ISSUE TITLE
Please update the documentation and buildwin.cmd concerning supported Visual Studio versions

### ISSUE THREAD

**Issue by paralaxsd** [pocoproject/poco#2533]
#### Expected behavior
Support for VS 2013 as documented in https://github.com/pocoproject/poco/blob/master/README:
"Microsoft Visual Studio 2008 or newer is required to build the POCO C++ Libraries on
Windows platforms."

#### Actual behavior
Unable to compile POCO on VS2013.
The compiler complains:
2>[...]\poco\Foundation\include\Poco/Platform_WIN32.h(88): fatal error C1189: #error :  "_MSC_VER >= 1900 (VS 2015) required"

#### Steps to reproduce the problem
generate VS2013 Win64 solution with cmake:
md cmake_build
cd cmake_build
cmake -G "Visual Studio 12 2013 Win64" ..
Try to compile Poco.sln with VS2013

#### POCO version
Latest master as of November 6th 2018 (ID: 13eda19cd1c2685113b535da7bf36aa88dfdaa5d)

#### Compiler and version
VS 2013 Update 5

#### Operating system and version
Windows 10 V1803

**Comment by zosrothko** [comment]
Only `poco-1.9.x` supports VS2013 up to VS2017. You are compiling the `master` branch while you should pickup the `poco-1.9.1` branch.

**Comment by paralaxsd** [comment]
Thanks that's good to know but I fear to no avail:

Checking out branch `poco-1.9.1` and building via cmake produces two issues:

1.) the cmake script detects C++11 support but fails later because VS 2013 [does not support default move constructors](https://blogs.msdn.microsoft.com/vcblog/2014/11/17/c111417-features-in-vs-2015-preview/):

```
CMake Error in Foundation/CMakeLists.txt:
  The compiler feature "cxx_defaulted_move_initializers" is not known to CXX
  compiler

  "MSVC"

  version 18.0.40629.0.
```

So I disabled cpp11 support:
`cmake -G "Visual Studio 12 2013 Win64" -DDISABLE_CPP11=ON ..`

This allows the script to run through and generate a `poco.sln` solution file. However this brings me to

2.) when building the solution from VS 2013, the foundations project fails with a myriad of errors of the form:
`2>[...]\poco\Foundation\include\Poco/ordered_hash.h(117): error C3646: 'noexcept' : unknown override specifier`

VS 2013 sadly [does not support noexcept](https://blogs.msdn.microsoft.com/vcblog/2014/11/17/c111417-features-in-vs-2015-preview/).
Affected files include `ordered_hash.h,` `ordered_map.h` and `ordered_set.h`.

**Comment by obiltschnig** [comment]
Please use the 1.9.0 release for now (which is confirmed to work with VS versions back to VS 2008 when using the included VS project files), as 1.9.1 is not yet officially released.

**Comment by paralaxsd** [comment]
Thanks, I can reconfirm that for a default option cmake build on 1.9.0!

**Comment by paralaxsd** [comment]
I have a follow up issue for the 1.9.0 branch that trips up my CI server.

It seems that the openssl submodule that's referenced is invalid. It's ok e.g. for the `1.9.1` branch.

Successful recursive checkout of `1.9.1`:
```
C:\tmp\poco>git checkout poco-1.9.1
Checking out files: 100% (2073/2073), done.
Switched to a new branch 'poco-1.9.1'
Branch 'poco-1.9.1' set up to track remote branch 'poco-1.9.1' from 'origin'.

C:\tmp\poco>git submodule update --init --recursive
Submodule path 'gradle': checked out 'cde5722cd5e9b66fb7471ef5f18b43eee057ccb6'
Submodule path 'openssl': checked out '0c6d16ec85f80ea3ce05a8f2ff52c1b3ba240a41'
```

Failing recursive checkout of `1.9.0`:
```
C:\tmp\poco>git checkout poco-1.9.0
Checking out files: 100% (2073/2073), done.
Switched to a new branch 'poco-1.9.0'
Branch 'poco-1.9.0' set up to track remote branch 'poco-1.9.0' from 'origin'.

C:\tmp\poco>git submodule update --init --recursive
Submodule path 'gradle': checked out '73b60316d69e239902711f32dca95f6d97aa257c'
error: Server does not allow request for unadvertised object 26b1673caad94a702b6d694f48f917a283b30777
Fetched in submodule path 'openssl', but it did not contain 26b1673caad94a702b6d694f48f917a283b30777. Direct fetching of that commit failed.
```

I guess only you can fix that in the repository, isn't it?

**Comment by zosrothko** [comment]
Fixed with commit `commit 50f1487dd4b3045bb76cc376c8a4b41f49e70c32 (HEAD -> poco-1.9.0, rigin/poco-1.9.0)`
Commands to execute:
```
git submodule deinit -f openssl
rd /q /s openssl
git submodule update --init --recursive --remote openssl
```

**Comment by paralaxsd** [comment]
Thanks for your quick response! Unfortunately I'm still at an impasse:

While I can manually initialize the sub module by forcing an update from the remote tracking branch I unfortunately don't have that option on my CI server ([TeamCity ](https://www.jetbrains.com/teamcity/)to be exact).

The `openssl` submodule in `1.9.0` still points to [26b1673](https://github.com/pocoproject/openssl/tree/26b1673caad94a702b6d694f48f917a283b30777). 

Wouldn't it work to checkout master (or develop [as hinted](https://github.com/pocoproject/poco/commit/50f1487dd4b3045bb76cc376c8a4b41f49e70c32)) in the `openssl` directory and commit the changed sub module pointer?

**Comment by zosrothko** [comment]
It would work, but this is the responsability of @aleks-f, and I would not overcome it. BTW, I do not know about TeamCity, but in AppVeyor or Travis, there is a way to deactivate the implicit git submodule command and add the git submodule --remote as an additional command.

**Comment by paralaxsd** [comment]
I see your point. I got CI running again by preventing recursive updates and updating the repo with a script.

Since `1.9.1` doesn't have this issue and it should still support VS 2013 when it's ready this should solve itself with time.

**Comment by aleks-f** [comment]
@zosrothko if committing only submodule pointer change, then it's ok to do it on 1.9.0 master - we do not want release branch to be broken

all 1.x versions support back to VS90, develop (future 2.0) to vs140
